/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author Afei
 */
public class ScoreDisplayFrame extends javax.swing.JFrame {

    /**
     * Creates new form ScoreDisplayFrame
     */
    public ScoreDisplayFrame(int nilaiTotal) {
        initComponents(nilaiTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int nilaiTotal) {

        titlePanel = new javax.swing.JPanel();
        ScoreTitleLabel = new javax.swing.JLabel();
        ScorePanel = new javax.swing.JPanel();
        ScoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        titlePanel.setLayout(new java.awt.GridLayout());

        ScoreTitleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        ScoreTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreTitleLabel.setText("Your Score is.......");
        ScoreTitleLabel.setPreferredSize(new java.awt.Dimension(85, 100));
        titlePanel.add(ScoreTitleLabel);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        ScorePanel.setLayout(new java.awt.GridLayout());

        ScoreLabel.setFont(new java.awt.Font("Pristina", 0, 95)); // NOI18N
        ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreLabel.setText(new String(String.valueOf(nilaiTotal)) + " %");
        ScorePanel.add(ScoreLabel);

        getContentPane().add(ScorePanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(564, 394));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JPanel ScorePanel;
    private javax.swing.JLabel ScoreTitleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
