/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author Afei
 */
public class SelectMatkulDanBabFrame extends javax.swing.JFrame {
    int matkulId = 0;
    int bagianId = 0;
    boolean flag = false;
    /**
     * Creates new form SelectMatkulDanBabFrame
     */
    public SelectMatkulDanBabFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        titlePanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        MainContentPanel = new javax.swing.JPanel();
        PanelMatkul1 = new javax.swing.JPanel();
        Matkul1TitlePanel = new javax.swing.JPanel();
        Matkul1TitleLabel = new javax.swing.JLabel();
        ButtonsMatkul1Panel = new javax.swing.JPanel();
        Matkul1Bagian1Button = new javax.swing.JButton();
        Matkul1Bagian2Button = new javax.swing.JButton();
        Matkul1Bagian3Button = new javax.swing.JButton();
        Matkul1Bagian4Button = new javax.swing.JButton();
        PanelMatkul2 = new javax.swing.JPanel();
        Matkul2TitlePanel = new javax.swing.JPanel();
        Matkul2TitleLabel = new javax.swing.JLabel();
        ButtonsMatkul2Panel = new javax.swing.JPanel();
        Matkul2Bagian1Button = new javax.swing.JButton();
        Matkul2Bagian2Button = new javax.swing.JButton();
        Matkul2Bagian3Button = new javax.swing.JButton();
        Matkul2Bagian4Button = new javax.swing.JButton();
        PanelMatkul3 = new javax.swing.JPanel();
        Matkul3TitlePanel = new javax.swing.JPanel();
        Matkul3TitleLabel = new javax.swing.JLabel();
        ButtonsMatkul3Panel = new javax.swing.JPanel();
        Matkul3Bagian1Button = new javax.swing.JButton();
        Matkul3Bagian2Button = new javax.swing.JButton();
        Matkul3Bagian3Button = new javax.swing.JButton();
        Matkul3Bagian4Button = new javax.swing.JButton();
        PanelMatkul4 = new javax.swing.JPanel();
        Matkul4TitlePanel = new javax.swing.JPanel();
        Matkul4TitleLabel = new javax.swing.JLabel();
        ButtonsMatkul4Panel = new javax.swing.JPanel();
        Matkul4Bagian1Button = new javax.swing.JButton();
        Matkul4Bagian2Button = new javax.swing.JButton();
        Matkul4Bagian3Button = new javax.swing.JButton();
        Matkul4Bagian4Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titlePanel.setMinimumSize(new java.awt.Dimension(198, 150));
        titlePanel.setPreferredSize(new java.awt.Dimension(0, 100));
        titlePanel.setLayout(new java.awt.GridLayout(1, 0));

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Pilihan Matkul dan Bab yang Tersedia");
        titlePanel.add(TitleLabel);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        MainContentPanel.setLayout(new javax.swing.BoxLayout(MainContentPanel, javax.swing.BoxLayout.Y_AXIS));

        PanelMatkul1.setBackground(new java.awt.Color(102, 255, 255));
        PanelMatkul1.setPreferredSize(new java.awt.Dimension(624, 86));
        PanelMatkul1.setLayout(new java.awt.BorderLayout());

        Matkul1TitlePanel.setLayout(new java.awt.BorderLayout());

        Matkul1TitleLabel.setText("Nama Matkul 1");
        Matkul1TitlePanel.add(Matkul1TitleLabel, java.awt.BorderLayout.CENTER);

        PanelMatkul1.add(Matkul1TitlePanel, java.awt.BorderLayout.NORTH);

        ButtonsMatkul1Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Matkul1Bagian1Button.setText("Bagian1");
        Matkul1Bagian1Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Matkul1Bagian1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul1Bagian1ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul1Panel.add(Matkul1Bagian1Button);

        Matkul1Bagian2Button.setText("Bagian2");
        Matkul1Bagian2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul1Bagian2ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul1Panel.add(Matkul1Bagian2Button);

        Matkul1Bagian3Button.setText("Bagian3");
        Matkul1Bagian3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul1Bagian3ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul1Panel.add(Matkul1Bagian3Button);

        Matkul1Bagian4Button.setText("Bagian4");
        Matkul1Bagian4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul1Bagian4ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul1Panel.add(Matkul1Bagian4Button);

        PanelMatkul1.add(ButtonsMatkul1Panel, java.awt.BorderLayout.CENTER);

        MainContentPanel.add(PanelMatkul1);

        PanelMatkul2.setBackground(new java.awt.Color(255, 51, 51));
        PanelMatkul2.setPreferredSize(new java.awt.Dimension(624, 86));
        PanelMatkul2.setLayout(new java.awt.BorderLayout());

        Matkul2TitlePanel.setLayout(new java.awt.GridLayout(1, 0));

        Matkul2TitleLabel.setText("Nama Matkul 2");
        Matkul2TitlePanel.add(Matkul2TitleLabel);

        PanelMatkul2.add(Matkul2TitlePanel, java.awt.BorderLayout.NORTH);

        ButtonsMatkul2Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Matkul2Bagian1Button.setText("Bagian1");
        Matkul2Bagian1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul2Bagian1ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul2Panel.add(Matkul2Bagian1Button);

        Matkul2Bagian2Button.setText("Bagian2");
        Matkul2Bagian2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul2Bagian2ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul2Panel.add(Matkul2Bagian2Button);

        Matkul2Bagian3Button.setText("Bagian3");
        Matkul2Bagian3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul2Bagian3ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul2Panel.add(Matkul2Bagian3Button);

        Matkul2Bagian4Button.setText("Bagian4");
        Matkul2Bagian4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul2Bagian4ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul2Panel.add(Matkul2Bagian4Button);

        PanelMatkul2.add(ButtonsMatkul2Panel, java.awt.BorderLayout.CENTER);

        MainContentPanel.add(PanelMatkul2);

        PanelMatkul3.setBackground(new java.awt.Color(0, 255, 102));
        PanelMatkul3.setPreferredSize(new java.awt.Dimension(624, 86));
        PanelMatkul3.setLayout(new java.awt.BorderLayout());

        Matkul3TitlePanel.setLayout(new java.awt.GridLayout(1, 0));

        Matkul3TitleLabel.setText("Nama Matkul 3");
        Matkul3TitlePanel.add(Matkul3TitleLabel);

        PanelMatkul3.add(Matkul3TitlePanel, java.awt.BorderLayout.NORTH);

        ButtonsMatkul3Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Matkul3Bagian1Button.setText("Bagian1");
        Matkul3Bagian1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul3Bagian1ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul3Panel.add(Matkul3Bagian1Button);

        Matkul3Bagian2Button.setText("Bagian2");
        Matkul3Bagian2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul3Bagian2ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul3Panel.add(Matkul3Bagian2Button);

        Matkul3Bagian3Button.setText("Bagian3");
        Matkul3Bagian3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul3Bagian3ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul3Panel.add(Matkul3Bagian3Button);

        Matkul3Bagian4Button.setText("Bagian4");
        Matkul3Bagian4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul3Bagian4ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul3Panel.add(Matkul3Bagian4Button);

        PanelMatkul3.add(ButtonsMatkul3Panel, java.awt.BorderLayout.CENTER);

        MainContentPanel.add(PanelMatkul3);

        PanelMatkul4.setBackground(new java.awt.Color(102, 102, 255));
        PanelMatkul4.setPreferredSize(new java.awt.Dimension(624, 86));
        PanelMatkul4.setLayout(new java.awt.BorderLayout());

        Matkul4TitlePanel.setLayout(new java.awt.GridLayout(1, 0));

        Matkul4TitleLabel.setText("Nama Matkul 4");
        Matkul4TitlePanel.add(Matkul4TitleLabel);

        PanelMatkul4.add(Matkul4TitlePanel, java.awt.BorderLayout.NORTH);

        ButtonsMatkul4Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Matkul4Bagian1Button.setText("Bagian1");
        Matkul4Bagian1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul4Bagian1ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul4Panel.add(Matkul4Bagian1Button);

        Matkul4Bagian2Button.setText("Bagian2");
        Matkul4Bagian2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul4Bagian2ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul4Panel.add(Matkul4Bagian2Button);

        Matkul4Bagian3Button.setText("Bagian3");
        Matkul4Bagian3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul4Bagian3ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul4Panel.add(Matkul4Bagian3Button);

        Matkul4Bagian4Button.setText("Bagian4");
        Matkul4Bagian4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    Matkul4Bagian4ButtonActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        ButtonsMatkul4Panel.add(Matkul4Bagian4Button);

        PanelMatkul4.add(ButtonsMatkul4Panel, java.awt.BorderLayout.CENTER);

        MainContentPanel.add(PanelMatkul4);

        getContentPane().add(MainContentPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(638, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Matkul2Bagian3ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul2Bagian3ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul2Bagian3Button){
            matkulId = 2;
            bagianId = 3;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul2Bagian3ButtonActionPerformed

    private void Matkul1Bagian1ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul1Bagian1ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul1Bagian1Button){
            matkulId = 1;
            bagianId = 1;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul1Bagian1ButtonActionPerformed

    private void Matkul1Bagian2ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul1Bagian2ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul1Bagian2Button){
            matkulId = 1;
            bagianId = 2;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul1Bagian2ButtonActionPerformed

    private void Matkul1Bagian3ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul1Bagian3ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul1Bagian3Button){
            matkulId = 1;
            bagianId = 3;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul1Bagian3ButtonActionPerformed

    private void Matkul1Bagian4ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul1Bagian4ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul1Bagian4Button){
            matkulId = 1;
            bagianId = 4;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul1Bagian4ButtonActionPerformed

    private void Matkul2Bagian1ButtonActionPerformed(java.awt.event.ActionEvent evt)throws SQLException{//GEN-FIRST:event_Matkul2Bagian1ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul2Bagian1Button){
            matkulId = 2;
            bagianId = 1;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul2Bagian1ButtonActionPerformed

    private void Matkul2Bagian2ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul2Bagian2ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul2Bagian2Button){
            matkulId = 2;
            bagianId = 2;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul2Bagian2ButtonActionPerformed

    private void Matkul2Bagian4ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException{//GEN-FIRST:event_Matkul2Bagian4ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul2Bagian4Button){
            matkulId = 2;
            bagianId = 4;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul2Bagian4ButtonActionPerformed

    private void Matkul3Bagian1ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul3Bagian1ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul3Bagian1Button){
            matkulId = 3;
            bagianId = 1;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul3Bagian1ButtonActionPerformed

    private void Matkul3Bagian2ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul3Bagian2ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul3Bagian2Button){
            matkulId = 3;
            bagianId = 2;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul3Bagian2ButtonActionPerformed

    private void Matkul3Bagian3ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul3Bagian3ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul3Bagian3Button){
            matkulId = 3;
            bagianId = 3;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul3Bagian3ButtonActionPerformed

    private void Matkul3Bagian4ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul3Bagian4ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul3Bagian4Button){
            matkulId = 3;
            bagianId = 4;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul3Bagian4ButtonActionPerformed

    private void Matkul4Bagian1ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul4Bagian1ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul4Bagian1Button){
            matkulId = 4;
            bagianId = 1;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul4Bagian1ButtonActionPerformed

    private void Matkul4Bagian2ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul4Bagian2ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul4Bagian2Button){
            matkulId = 4;
            bagianId = 2;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul4Bagian2ButtonActionPerformed

    private void Matkul4Bagian3ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul4Bagian3ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul4Bagian3Button){
            matkulId = 4;
            bagianId = 3;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul4Bagian3ButtonActionPerformed

    private void Matkul4Bagian4ButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_Matkul4Bagian4ButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==Matkul4Bagian4Button){
            matkulId = 4;
            bagianId = 4;
            AnyButtonPressed(evt);
        }
    }//GEN-LAST:event_Matkul4Bagian4ButtonActionPerformed

    private void AnyButtonPressed(java.awt.event.ActionEvent evt) throws SQLException {
        this.setVisible(false);
        flag = true;
        new MainFrame(this.matkulId, this.bagianId).setVisible(true);
//        System.out.println(matkulId + " " + bagianId);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsMatkul1Panel;
    private javax.swing.JPanel ButtonsMatkul2Panel;
    private javax.swing.JPanel ButtonsMatkul3Panel;
    private javax.swing.JPanel ButtonsMatkul4Panel;
    private javax.swing.JPanel MainContentPanel;
    private javax.swing.JButton Matkul1Bagian1Button;
    private javax.swing.JButton Matkul1Bagian2Button;
    private javax.swing.JButton Matkul1Bagian3Button;
    private javax.swing.JButton Matkul1Bagian4Button;
    private javax.swing.JLabel Matkul1TitleLabel;
    private javax.swing.JPanel Matkul1TitlePanel;
    private javax.swing.JButton Matkul2Bagian1Button;
    private javax.swing.JButton Matkul2Bagian2Button;
    private javax.swing.JButton Matkul2Bagian3Button;
    private javax.swing.JButton Matkul2Bagian4Button;
    private javax.swing.JLabel Matkul2TitleLabel;
    private javax.swing.JPanel Matkul2TitlePanel;
    private javax.swing.JButton Matkul3Bagian1Button;
    private javax.swing.JButton Matkul3Bagian2Button;
    private javax.swing.JButton Matkul3Bagian3Button;
    private javax.swing.JButton Matkul3Bagian4Button;
    private javax.swing.JLabel Matkul3TitleLabel;
    private javax.swing.JPanel Matkul3TitlePanel;
    private javax.swing.JButton Matkul4Bagian1Button;
    private javax.swing.JButton Matkul4Bagian2Button;
    private javax.swing.JButton Matkul4Bagian3Button;
    private javax.swing.JButton Matkul4Bagian4Button;
    private javax.swing.JLabel Matkul4TitleLabel;
    private javax.swing.JPanel Matkul4TitlePanel;
    private javax.swing.JPanel PanelMatkul1;
    private javax.swing.JPanel PanelMatkul2;
    private javax.swing.JPanel PanelMatkul3;
    private javax.swing.JPanel PanelMatkul4;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
